server:
  servlet:
    context-path: /wechat/demo
  port: 8081

wechat:
  config:
    #配置一个文字的模板ID
    singleTemplateId:
    template:
      #早安模板
      morningTemplate:
        #模板ID
        templateId: 	HnCu9bIamcrPrciZ-rMW2xv097ZWMK2KF1belOeQHxc
        #是否关注的用户全发送，ture为是，当值为ture时，sendOpenId 为排除发送对象的微信用户，当值为false为否，sendOpenId为发送对象的微信用户
        allSend: true
        filterOpenIds:
#          - oK0U562Y5ijqYRpGUtNRs0vxxxWU
        parameter:
          #这是默认的设置，如果有用户没设置参数，就按此参数
          default:
            #早安话语
            title: 美好的一天开始啦
            #你们的相遇时间
            meetDate: '2019-01-31'
            city: 上海
            #居住地点，高德地图api下载查询 https://lbs.amap.com/api/webservice/download
            cityCode: 440100
            constellation: 
          #把‘填写你的需要特定配置的微信用户号’覆盖位微信用户ID，可以对照正确填写好的配置示例，多用户可以按照格式继续添加下去
          oZDFF6Fbbqpd4MJL2KxsbS5RdR84
      #颜文字模板
      emoticonsTemplate:
        templateId: 	HnCu9bIamcrPrciZ-rMW2xv097ZWMK2KF1belOeQHxc
        allSend: true
        filterOpenIds:
        parameter:
          default:
            title: 1
#发送者个人信息
personal:
  info:
    constellation: 双子座

